### ISSUE TITLE
Wrong matching apache tomcat - Metasploitable2

### ISSUE THREAD

**Issue by dmknght** [dmknght/BruteforceHTTP#1]
Target URL:
`http://192.168.56.101:8180/admin/`
`http://192.168.56.101:8180/admin/index.jsp`
List: `tomcat`
Message (logged fail)
```
Invalid username or password
To try again, click here
```

**Comment by chasingdreamm** [comment]
@dmknght how can I contact you?

**Comment by chasingdreamm** [comment]
Turn on messagin on twitter please

**Comment by dmknght** [comment]
Fixed via latest update
