### ISSUE TITLE
can't detect login form - cpanel

### ISSUE THREAD

**Issue by dmknght** [dmknght/BruteforceHTTP#7]
http://www.chuabaidinhninhbinh.vn:2082/

**Comment by ZeroX-DG** [comment]
Well, this is a solution I came up with. This could be applied to better detect the form. Basically it's just go to the site, find all the form, and score each form base on some certain rules. After that, you can pick the form with the highest score (highest posibility to be the login form). I call that login form detective.
https://gist.github.com/ZeroX-DG/ae77a2a6a27748a46d7efd1b45e7155f

**Comment by dmknght** [comment]
closed via latest commit
